version: 2

updates:

- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: '08:00'
  open-pull-requests-limit: 99

- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: '08:00'
  open-pull-requests-limit: 99

- package-ecosystem: pip
  directory: "/tests"
  schedule:
    interval: daily
    time: '08:00'
  open-pull-requests-limit: 99

